#!/bin/sh

echo Cleaning...
rm -rf autom4te.cache
rm -f config.h config.h.in config.log config.cache
rm -f config.sub config.status config.guess
rm -f configure
rm -f depcomp install-sh libtool ltmain.sh missing
rm -f mkinstalldirs acconfig.h stamp-h1

export WANT_AUTOMAKE='1.6'
export WANT_AUTOCONF_2_5=1

echo Running libtoolize... && \
libtoolize && \
echo Running aclocal... && \
aclocal -I scripts $ACLOCAL_FLAGS && \
echo Running autoheader... && \
autoheader && \
echo Running autoconf... && \
autoconf && \
echo Running automake... && \
automake --add-missing --gnu
echo Done
