Document: libopeninput
Title: Debian libopeninput Manual
Author: <insert document author here>
Abstract: This manual describes what libopeninput is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libopeninput/libopeninput.sgml.gz

Format: postscript
Files: /usr/share/doc/libopeninput/libopeninput.ps.gz

Format: text
Files: /usr/share/doc/libopeninput/libopeninput.text.gz

Format: HTML
Index: /usr/share/doc/libopeninput/html/index.html
Files: /usr/share/doc/libopeninput/html/*.html

  
