Document: libsinp
Title: Debian libsinp Manual
Author: <insert document author here>
Abstract: This manual describes what libsinp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsinp/libsinp.sgml.gz

Format: postscript
Files: /usr/share/doc/libsinp/libsinp.ps.gz

Format: text
Files: /usr/share/doc/libsinp/libsinp.text.gz

Format: HTML
Index: /usr/share/doc/libsinp/html/index.html
Files: /usr/share/doc/libsinp/html/*.html

  
